name: Build AndUEDumper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make git wget unzip
    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip android-ndk-r25c-linux.zip
    - name: Build
      run: |
        export NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r25c
        make clean && make
      working-directory: ./AndUEDumper
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: AndUEDumper-build
        path: AndUEDumper/build/
