name: Build AndUEDumper

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: sudo apt-get install -y make git wget unzip

    - name: Download and Extract Android NDK r25c
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip android-ndk-r25c-linux.zip

    - name: Build Project (Menggunakan NDK)
      run: |
        export NDK_HOME=$PWD/android-ndk-r25c
        cd AndUEDumper/AndUEDumper
        make clean && make

    - name: Upload Hasil Build
      uses: actions/upload-artifact@v3
      with:
        name: AndUEDumper-build
        path: AndUEDumper/build/
        
